seed: 42

data:
  processed_dir: data/processed/uk
  sequence_length: 8
  batch_size: 64
  num_workers: 0

model:
  in_channels: 30
  cnn_channels: [32, 32]
  kernel_sizes: [3, 3]
  pool_size: 2
  fc_dim: 128
  attn_spatial_dim: 64
  attn_temporal_dim: 64
  lstm_hidden: 128
  lstm_layers: 2
  dropout: 0.2
  cnn_dropout: 0.3

train:
  optimizer: adam
  lr: 0.001
  weight_decay: 1.113e-05
  epochs: 100
  epochs_alt: 200
  early_stopping_patience: 10
  grad_clip: 1.0
  sample_weighting: {1: 1.0, 2: 1.5, 3: 2.0}
  use_cv: false

cv:
  folds: 10

balance:
  smote: null
  undersample: {sampling_strategy: {1: 1, 2: 80, 3: 20}}

metrics:
  mae: true
  classification: {enabled: true}

output:
  dir: outputs
  checkpoint: best.pt